### ISSUE TITLE
Cosmetic 'Vbox' error

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-docker-images#384] opened 2022-10-07 18:17 UTC
When I run the following code on the Pangeo or m2lines cloud deployments in the regular notebooks environment, I get an error (also being experienced by @paigem): 

```
from dask_gateway import Gateway
from dask.distributed import Client

gateway = Gateway()
options = gateway.cluster_options()
options.worker_memory = 6
cluster = gateway.new_cluster(options)
cluster.adapt(minimum=1,maximum=5)
cluster
```
I get the error:
<img width="834" alt="Screen Shot 2022-10-07 at 2 16 51 PM" src="https://user-images.githubusercontent.com/18236610/194623612-b0211341-8f7f-4ee0-8f72-ce5d54828bb2.png">

Things still work fine - cluster is activated, but not sure why this error is being produced.

**Comment by guillaumeeb** [comment] 2022-10-07 18:29
Hi @dhruvbalwada, thanks! This issue is a duplicate of https://github.com/pangeo-data/pangeo-docker-images/issues/382.

**Closed by guillaumeeb** 2022-10-07 18:29 UTC

**Comment by dhruvbalwada** [comment] 2022-10-07 18:31
Oops, sorry should have looked more carefully before posting.
